name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Esto se ejecuta al hacer push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/custom_nginx:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/custom_nginx:latest

    - name: Logout from DockerHub
      run: docker logout
